Or apk
yehiyam/coronaCv-backend pull request #3
Opened 2020-04-26 09:27 UTC by or2511

Added APK - storage to the backend (For now not limited to only APK files, works with every file).

Can GET : 
 * ApkName\ApkVersion,
 * ApkName\list
 * ApkName\get_version (for the latest)
Can POST: 
* ApkName\ApkVersion with the application. (Upload the to the server).

2020-04-26 10:10 UTC, yehiyam requested changes

2020-04-26 10:10 UTC, yehiyam commented on config.js
> +        filesLocation: "C:\\Applications"
use process.env to be able to change it when running
also, change the default to something that will work in ubuntu

2020-04-26 10:10 UTC, yehiyam commented on lib/routes/application.js
> +path = require('path');
need const

2020-04-26 10:10 UTC, yehiyam commented on lib/routes/application.js
> +                res.send(ret)
isn't the reply in json? if so you need to send it with res.json to set the content type headers

2020-04-26 10:10 UTC, yehiyam commented on lib/routes/application.js
> +                if (!ret){
you are using ret before checking if it is defined

2020-04-26 10:10 UTC, yehiyam commented on lib/routes/application.js
> +                var stat = fs.statSync(filePath);
better use the async versions
you can use promisify to turn fs.stat into an async function
// at the top of the file
const {promisify}=require('util')
const stat=promisify(fs.stat)

// to use:
const fileStat=await stat(file)

2020-04-26 10:10 UTC, yehiyam commented on lib/routes/application.js
> +                var stat = fs.statSync(filePath);
use let of const and not var

2020-04-26 10:10 UTC, yehiyam commented on lib/routes/application.js
> +                if (!ret){
same as above. if ret us not defined, it will crash in line 71

2020-04-26 10:10 UTC, yehiyam commented on lib/services/application.js
> +const monitorList = async () => {
monitorList here? copy/paste error?

2020-04-26 10:10 UTC, yehiyam commented on lib/storage/mongo.js
> +            let query = (name) ? { name } : {}
name cannot be null here because you check for it in line 267

2020-04-26 10:10 UTC, yehiyam commented on lib/storage/mongo.js
> +            doc.markModified("path");
from what I understand (about mongodb) markModified is only needed for types that are not known by mongo. Not needed for a simple String field

2020-04-26 10:30 UTC, or2511 commented on lib/routes/application.js
> +                res.send(ret)
The function returns list with the versions of the application, not json.
Example: ["1.2","1.4"]

2020-04-26 10:32 UTC, or2511 commented on lib/routes/application.js
> +                if (!ret){
Correct, I have deleted part of the code and forget to move it to the right line.
I will fix it.

2020-04-26 10:39 UTC, yehiyam commented on lib/routes/application.js
> +                res.send(ret)
Array of strings is a valid json. In any case I think it is better to return json so applications can parse it

2020-04-26 10:44 UTC, or2511 commented on lib/routes/application.js
> +                res.send(ret)
I thought json format is only {key : value}.
I will change it to res.json(ret).

2020-04-26 11:06 UTC, or2511 commented on lib/routes/application.js
> +                var stat = fs.statSync(filePath);
very nice, changed it.

2020-04-26 11:13 UTC, or2511 commented on config.js
> +        filesLocation: "C:\\Applications"
I will set it with process.env.
Do you have preferred linux location?

2020-04-26 12:53 UTC, yehiyam requested changes

2020-04-26 12:53 UTC, yehiyam commented on lib/routes/application.js
> +                    res.end();
res.end() doesn't return. the execution continues to the next line.
either do return res.end() or return on the next line

2020-04-26 12:53 UTC, yehiyam commented on lib/services/application.js
> +        if (!fs.existsSync(config.applicationConfig.filesLocation)){
use promisify and await (not sync)

2020-04-26 12:59 UTC, yehiyam commented on lib/services/application.js
> +        var form = new formidable.IncomingForm();
I'd rather you put the form handling in the route, and not pass the request object (which is express specific) to the service.

2020-04-26 13:07 UTC, yehiyam requested changes

2020-04-26 13:07 UTC, yehiyam commented on lib/routes/application.js
> +                    'Content-Type': 'application/' + type,
should be fileType

2020-04-27 06:31 UTC, yehiyam requested changes

2020-04-27 06:31 UTC, yehiyam commented on lib/routes/application.js
> +    router.get('/:name/list', async (req, res, next) => {
this endpoint conflicts with `/:name/:version`

2020-04-30 13:55 UTC, yehiyam approved these changes

2020-04-30 13:55 UTC, merged